# The main pipeline for training_databricks_etl_bi_ia

resources:
  pipelines:
    training_databricks_etl_bi_ia_etl:
      name: training_databricks_etl_bi_ia_etl
      catalog: ${var.catalog}
      schema: ${var.schema}
      serverless: true
      root_path: "../src/training_databricks_etl_bi_ia_etl"

      libraries:
        - glob:
            include: ../src/training_databricks_etl_bi_ia_etl/transformations/**

      environment:
        dependencies:
          # We include every dependency defined by pyproject.toml by defining an editable environment
          # that points to the folder where pyproject.toml is deployed.
          - --editable ${workspace.file_path}
